version: "3.8"
services:
  aws:
    image: organs/awscli 
    environment:
      AWS_REGION: "${AWS_REGION}"
      AWS-DEFAULT-REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - .:/app
    working_dir: /app

  website:
    build: 
      context: .
    image: "${AWS_IMAGE}"
    ports: 
      - 8000:8000